GET https://kebele-id-renewal-and-issuing-backend.onrender.com/api/v1/resident/

### 
POST https://kebele-id-renewal-and-issuing-backend.onrender.com/api/v1/admin/login/
Content-Type: application/json

{
      "phoneNumber": "0912131213",
       "password": "123456"
}